weights: ./fold2/exp/weights/last.pt
cfg: ''
data: ./data/coco_fold2.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 300
batch_size: 8
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 2
project: fold2
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: 1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: fold2/exp
